# permissions for end users to edit ipcidrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipcidr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubipam
    app.kubernetes.io/part-of: kubipam
    app.kubernetes.io/managed-by: kustomize
  name: ipcidr-editor-role
rules:
- apiGroups:
  - ipam.amoyel.fr
  resources:
  - ipcidrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.amoyel.fr
  resources:
  - ipcidrs/status
  verbs:
  - get
